services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./agora_site/media/data:/app/agora_site/media/data
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=agora_site.settings
      - C_FORCE_ROOT=true
    depends_on:
      - rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # interfaz web de RabbitMQ
      - "5672:5672"    # puerto AMQP para Celery
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=agora
      - RABBITMQ_DEFAULT_PASS=agora
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  rabbitmq_data:
